// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

namespace Lotto649
{
    public partial class Slot2
    {
        /// <summary>
        /// model input class for Slot2.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(5)]
            [ColumnName(@"col5")]
            public float Col5 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Slot2.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"col5")]
            public float[] Col5 { get; set; }

            [ColumnName(@"col5_LB")]
            public float[] Col5_LB { get; set; }

            [ColumnName(@"col5_UB")]
            public float[] Col5_UB { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"G:\projects\loabletech\LottoML.net\lotto649\slot2.mlnet");

        public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input, horizon);
        }

        private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }
    }
}

