// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace LottoML_net6
{
    public partial class _649_weather
    {
        /// <summary>
        /// model input class for _649_weather.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"temp")]
            public float Temp { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"humidity")]
            public float Humidity { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"pressure")]
            public float Pressure { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"slot")]
            public float Slot { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"target")]
            public float Target { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for _649_weather.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"temp")]
            public float Temp { get; set; }

            [ColumnName(@"humidity")]
            public float Humidity { get; set; }

            [ColumnName(@"pressure")]
            public float Pressure { get; set; }

            [ColumnName(@"slot")]
            public float Slot { get; set; }

            [ColumnName(@"target")]
            public float Target { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("649-weather.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
