// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace LottoML_net6
{
    public partial class Classification_645
    {
        /// <summary>
        /// model input class for Classification_645.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"slot1")]
            public float Slot1 { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"slot2")]
            public float Slot2 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"slot3")]
            public float Slot3 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"slot4")]
            public float Slot4 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"slot5")]
            public float Slot5 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"slot6")]
            public float Slot6 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"haswinner")]
            public bool Haswinner { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Classification_645.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"slot1")]
            public float Slot1 { get; set; }

            [ColumnName(@"slot2")]
            public float Slot2 { get; set; }

            [ColumnName(@"slot3")]
            public float Slot3 { get; set; }

            [ColumnName(@"slot4")]
            public float Slot4 { get; set; }

            [ColumnName(@"slot5")]
            public float Slot5 { get; set; }

            [ColumnName(@"slot6")]
            public float Slot6 { get; set; }

            [ColumnName(@"haswinner")]
            public bool Haswinner { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("classification-645.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
