// This file was auto-generated by ML.NET Model Builder.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Classification_645_ConsoleApp2
{
    public partial class Classification_645
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"slot1", @"slot1"),new InputOutputColumnPair(@"slot2", @"slot2"),new InputOutputColumnPair(@"slot3", @"slot3"),new InputOutputColumnPair(@"slot4", @"slot4"),new InputOutputColumnPair(@"slot5", @"slot5"),new InputOutputColumnPair(@"slot6", @"slot6")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"slot1",@"slot2",@"slot3",@"slot4",@"slot5",@"slot6"}))      
                                    .Append(mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=6,MinimumExampleCountPerLeaf=12,NumberOfTrees=4,MaximumBinCountPerFeature=310,FeatureFraction=0.86942925517641,LearningRate=0.0388293224736222,LabelColumnName=@"haswinner",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
