
// This file was auto-generated by ML.NET Model Builder. 

using Classification_645_ConsoleApp2;

// Create single instance of sample data from first line of dataset for model input
Classification_645.ModelInput sampleData = new Classification_645.ModelInput()
{
    Slot1 = 9F,
    Slot2 = 19F,
    Slot3 = 28F,
    Slot4 = 33F,
    Slot5 = 34F,
    Slot6 = 45F,
};

// Make a single prediction on the sample data and print results
var predictionResult = Classification_645.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Haswinner with predicted Haswinner from sample data...\n\n");


Console.WriteLine($"Slot1: {9F}");
Console.WriteLine($"Slot2: {19F}");
Console.WriteLine($"Slot3: {28F}");
Console.WriteLine($"Slot4: {33F}");
Console.WriteLine($"Slot5: {34F}");
Console.WriteLine($"Slot6: {45F}");


Console.WriteLine($"\n\nPredicted Haswinner: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

